// resources/js/pages/agents/AgentEditModal.vue
<script setup lang="ts">
import { usePage } from '@inertiajs/vue3'
import { computed, ref } from 'vue'
import Modal from '@/components/ui/Modal.vue'
import { cancelBtnClass, inputClass, labelClass, submitBtnClass } from '@/components/ui/styles'
import type { AgentFlags, ProjectAgent } from '@/queries/agentQuery'
import { useAppLayoutStore } from '@/stores/appLayoutStore'
import { color } from '@/tokens'
import { AGENT_TYPE_COLORS, AGENT_TYPE_LABELS, DEFAULT_MODEL, DEFAULT_PROVIDER } from '@/types/agent'
import { FALLBACK_PROVIDERS, modelsForProvider, type GlobalSettings } from '@/types/provider'
import AgentLaunchOptions from './AgentLaunchOptions.vue'

/**
 * Self-contained "Edit Agent" modal. Renders its own `trigger` slot and owns
 * the open state via the reusable Modal. Wrap the trigger in a
 * stop-propagation container when it lives inside a clickable row so opening
 * the modal doesn't also trigger the row.
 */
const props = defineProps<{ agent: ProjectAgent }>()
const emit = defineEmits<{ openChange: [open: boolean] }>()

const PANEL_CLASS = 'bg-modal border border-stroke rounded-lg p-6 w-[600px] max-w-[95vw] max-h-[90vh] overflow-y-auto flex flex-col'

const page = usePage<{ global_settings?: GlobalSettings }>()
const layout = useAppLayoutStore()
const providers = computed(() => page.props.global_settings?.providers ?? FALLBACK_PROVIDERS)

const name = ref('')
const agentType = ref('')
const description = ref('')
const provider = ref('')
const model = ref('')
const systemPrompt = ref('')
const flags = ref<AgentFlags>({})
const planMode = ref(false)
const error = ref('')
const loading = ref(false)

const models = computed(() => modelsForProvider(providers.value, provider.value))

function loadFromAgent() {
    const a = props.agent
    name.value = a.name
    agentType.value = a.agent_type
    description.value = a.description ?? ''
    provider.value = a.provider ?? DEFAULT_PROVIDER
    model.value = a.model ?? DEFAULT_MODEL
    systemPrompt.value = a.system_prompt ?? ''
    flags.value = a.flags ?? {}
    planMode.value = !!a.plan_mode
    error.value = ''
    loading.value = false
}

function onOpenChange(open: boolean) {
    if (open) loadFromAgent()
    emit('openChange', open)
}

function onProviderChange() {
    model.value = models.value[0] ?? ''
}

function typeStyle(type: string) {
    const typeColor = AGENT_TYPE_COLORS[type] ?? color.accent
    const active = agentType.value === type
    return {
        borderColor: active ? typeColor : color.borderMuted,
        background: active ? `${typeColor}18` : 'transparent',
        color: active ? typeColor : color.textMuted,
    }
}

async function handleSubmit(close: () => void) {
    const trimmedName = name.value.trim()
    if (!trimmedName) { error.value = 'Name is required'; return }
    error.value = ''
    loading.value = true
    try {
        const res = await fetch(`/api/agents/${props.agent.id}`, {
            method: 'PATCH',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                name: trimmedName,
                agent_type: agentType.value,
                description: description.value.trim() || null,
                provider: provider.value,
                model: model.value,
                system_prompt: systemPrompt.value.trim() || null,
                flags: flags.value,
                plan_mode: planMode.value,
            }),
        })
        const data = await res.json()
        if (!res.ok) { error.value = data.error ?? 'Something went wrong'; return }
        layout.agentHook.invalidate()
        close()
    } catch {
        error.value = 'Network error'
    } finally {
        loading.value = false
    }
}
</script>

<template>
    <Modal aria-label="Edit agent" :panel-class="PANEL_CLASS" @open-change="onOpenChange">
        <template #trigger><slot name="trigger" /></template>
        <template #default="{ close }">
            <form class="flex flex-col gap-3.5" @submit.prevent="handleSubmit(close)">
                <h2 class="m-0 text-zinc-900 text-[15px] font-semibold">Edit Agent</h2>

                <span v-if="error" class="text-danger text-[12px]">{{ error }}</span>

                <div class="flex flex-col gap-1.5">
                    <span :class="labelClass">Type</span>
                    <div class="flex gap-2 flex-wrap">
                        <button
                            v-for="(label, type) in AGENT_TYPE_LABELS"
                            :key="type"
                            type="button"
                            data-testid="agent-type"
                            :class="['py-[5px] px-3 rounded border text-[12px] cursor-pointer', agentType === type ? 'font-semibold' : 'font-normal']"
                            :style="typeStyle(type)"
                            @click="agentType = type"
                        >
                            {{ label }}
                        </button>
                    </div>
                </div>

                <label class="flex flex-col gap-1">
                    <span :class="labelClass">Name</span>
                    <input v-model="name" name="name" autofocus placeholder="Agent name" required :class="[inputClass, 'w-full box-border']">
                </label>

                <label class="flex flex-col gap-1">
                    <span :class="labelClass">Description</span>
                    <input v-model="description" name="description" placeholder="Short description" :class="[inputClass, 'w-full box-border']">
                </label>

                <div class="flex gap-2.5">
                    <label class="w-[180px] flex flex-col gap-1">
                        <span :class="labelClass">Provider</span>
                        <select v-model="provider" name="provider" :class="[inputClass, 'w-full box-border']" @change="onProviderChange">
                            <option v-for="item in providers" :key="item.slug" :value="item.slug">{{ item.name }}</option>
                        </select>
                    </label>
                    <label class="flex-1 flex flex-col gap-1">
                        <span :class="labelClass">Model</span>
                        <select v-model="model" name="model" :class="[inputClass, 'w-full box-border']">
                            <option v-for="item in models" :key="item" :value="item">{{ item }}</option>
                        </select>
                    </label>
                </div>

                <label class="flex flex-col gap-1">
                    <span :class="labelClass">System Prompt</span>
                    <textarea
                        v-model="systemPrompt"
                        name="system_prompt"
                        placeholder="Instructions for this agent… (leave blank to use none)"
                        :rows="6"
                        :class="[inputClass, 'w-full box-border resize-y leading-normal']"
                    />
                </label>

                <AgentLaunchOptions v-model:flags="flags" v-model:plan-mode="planMode" />

                <div class="flex gap-2 justify-end pt-1">
                    <button type="button" :class="cancelBtnClass" @click="close">Cancel</button>
                    <button type="submit" :disabled="loading" :class="submitBtnClass" :style="{ opacity: loading ? 0.7 : 1 }">
                        {{ loading ? 'Saving…' : 'Save Changes' }}
                    </button>
                </div>
            </form>
        </template>
    </Modal>
</template>

// resources/js/components/agent/AgentEditModal.tsx
import { useEffect, useState } from 'react'
import { color } from '@/tokens'
import { type ProjectAgent, type AgentFlags, normalizeAgent } from '@/queries/agents'
import { AGENT_TYPE_LABELS, AGENT_TYPE_COLORS, MODELS } from '@/types/agent'
import { labelStyle, inputStyle, cancelBtnStyle, submitBtnStyle, flagRowStyle, toggleStyle } from '@/components/ui/styles'

// ─── Component ────────────────────────────────────────────────────────────────

export default function AgentEditModal({
    agent,
    onClose,
    onSaved,
}: {
    agent: ProjectAgent
    onClose: () => void
    onSaved: (updated: ProjectAgent) => void
}) {
    const [name, setName] = useState(agent.name)
    const [agentType, setAgentType] = useState(agent.agent_type)
    const [description, setDescription] = useState(agent.description ?? '')
    const [model, setModel] = useState(agent.model ?? 'claude-opus-4-8')
    const [systemPrompt, setSystemPrompt] = useState(agent.system_prompt ?? '')
    const [flags, setFlags] = useState<AgentFlags>(agent.flags ?? {})
    const [planMode, setPlanMode] = useState(!!agent.plan_mode)
    const [error, setError] = useState('')
    const [loading, setLoading] = useState(false)

    // Sync fields when the agent prop changes (e.g. modal re-opened for a different agent)
    useEffect(() => {
        setName(agent.name)
        setAgentType(agent.agent_type)
        setDescription(agent.description ?? '')
        setModel(agent.model ?? 'claude-opus-4-8')
        setSystemPrompt(agent.system_prompt ?? '')
        setFlags(agent.flags ?? {})
        setPlanMode(!!agent.plan_mode)
        setError('')
    }, [agent.id])

    function setFlag(key: keyof AgentFlags, value: boolean | number | null) {
        setFlags(prev => ({ ...prev, [key]: value }))
    }

    async function handleSubmit(e: React.FormEvent) {
        e.preventDefault()
        const trimmedName = name.trim()
        if (!trimmedName) { setError('Name is required'); return }
        setError('')
        setLoading(true)
        try {
            const res = await fetch(`/api/agents/${agent.id}`, {
                method: 'PATCH',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    name: trimmedName,
                    agent_type: agentType,
                    description: description.trim() || null,
                    model,
                    system_prompt: systemPrompt.trim() || null,
                    flags,
                    plan_mode: planMode,
                }),
            })
            const data = await res.json()
            if (!res.ok) { setError(data.error ?? 'Something went wrong'); return }
            onSaved(normalizeAgent(data.data))
            onClose()
        } catch {
            setError('Network error')
        } finally {
            setLoading(false)
        }
    }

    // Close on Escape
    useEffect(() => {
        function onKey(e: KeyboardEvent) { if (e.key === 'Escape') onClose() }
        document.addEventListener('keydown', onKey)
        return () => document.removeEventListener('keydown', onKey)
    }, [onClose])

    return (
        <div
            style={{
                position: 'fixed', inset: 0, background: color.overlay,
                display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 200,
            }}
            onClick={e => { if (e.target === e.currentTarget) onClose() }}
        >
            <div style={{
                background: color.bgModal, border: `1px solid ${color.borderMuted}`, borderRadius: '8px',
                padding: '24px', width: '600px', maxWidth: '95vw', maxHeight: '90vh', overflowY: 'auto',
                display: 'flex', flexDirection: 'column',
            }}>
                <form onSubmit={handleSubmit} style={{ display: 'flex', flexDirection: 'column', gap: '14px' }}>
                    <h2 style={{ margin: 0, color: color.textPrimary, fontSize: '15px', fontWeight: 600 }}>Edit Agent</h2>

                    {error && <span style={{ color: color.danger, fontSize: '12px' }}>{error}</span>}

                    {/* Type selector */}
                    <label style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                        <span style={labelStyle}>Type</span>
                        <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
                            {Object.entries(AGENT_TYPE_LABELS).map(([type, label]) => {
                                const active = agentType === type
                                return (
                                    <button
                                        key={type}
                                        type="button"
                                        onClick={() => setAgentType(type)}
                                        style={{
                                            padding: '5px 12px',
                                            borderRadius: '6px',
                                            border: `1px solid ${active ? AGENT_TYPE_COLORS[type] ?? color.accent : color.borderMuted}`,
                                            background: active ? `${AGENT_TYPE_COLORS[type] ?? color.accent}18` : 'transparent',
                                            color: active ? (AGENT_TYPE_COLORS[type] ?? color.accent) : color.textMuted,
                                            fontSize: '12px', fontWeight: active ? 600 : 400,
                                            cursor: 'pointer',
                                        }}
                                    >
                                        {label}
                                    </button>
                                )
                            })}
                        </div>
                    </label>

                    {/* Name */}
                    <label style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                        <span style={labelStyle}>Name</span>
                        <input
                            autoFocus
                            value={name}
                            onChange={e => setName(e.target.value)}
                            placeholder="Agent name"
                            required
                            style={{ ...inputStyle, width: '100%', boxSizing: 'border-box' as const }}
                        />
                    </label>

                    {/* Description */}
                    <label style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                        <span style={labelStyle}>Description</span>
                        <input
                            value={description}
                            onChange={e => setDescription(e.target.value)}
                            placeholder="Short description"
                            style={{ ...inputStyle, width: '100%', boxSizing: 'border-box' as const }}
                        />
                    </label>

                    {/* Model */}
                    <label style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                        <span style={labelStyle}>Model</span>
                        <select
                            value={model}
                            onChange={e => setModel(e.target.value)}
                            style={{ ...inputStyle, width: '100%', boxSizing: 'border-box' as const }}
                        >
                            {MODELS.map(m => <option key={m.value} value={m.value}>{m.label}</option>)}
                        </select>
                    </label>

                    {/* System Prompt */}
                    <label style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
                        <span style={labelStyle}>System Prompt</span>
                        <textarea
                            value={systemPrompt}
                            onChange={e => setSystemPrompt(e.target.value)}
                            placeholder="Instructions for this agent… (leave blank to use none)"
                            rows={6}
                            style={{
                                ...inputStyle,
                                width: '100%', boxSizing: 'border-box' as const,
                                resize: 'vertical' as const, lineHeight: 1.5,
                            }}
                        />
                    </label>

                    {/* Launch Options */}
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
                        <span style={labelStyle}>Launch Options</span>

                        {/* Skip Permissions */}
                        <div
                            style={flagRowStyle}
                            onClick={() => setFlag('dangerously_skip_permissions', !flags.dangerously_skip_permissions)}
                        >
                            <div>
                                <div style={{ fontSize: '12px', fontWeight: 500, color: color.textSecondary }}>Skip Permissions</div>
                                <div style={{ fontSize: '10px', color: color.textFaint }}>--dangerously-skip-permissions — no prompts</div>
                            </div>
                            <button
                                type="button"
                                style={toggleStyle(!!flags.dangerously_skip_permissions)}
                                onClick={e => e.stopPropagation()}
                                title="Toggle --dangerously-skip-permissions"
                            >
                                <span style={{
                                    position: 'absolute', top: '3px',
                                    left: flags.dangerously_skip_permissions ? '17px' : '3px',
                                    width: '12px', height: '12px', borderRadius: '50%',
                                    background: '#fff', transition: 'left 0.15s',
                                }} />
                            </button>
                        </div>

                        {/* Plan Mode */}
                        <div
                            style={flagRowStyle}
                            onClick={() => setPlanMode(p => !p)}
                        >
                            <div>
                                <div style={{ fontSize: '12px', fontWeight: 500, color: color.textSecondary }}>Plan Mode</div>
                                <div style={{ fontSize: '10px', color: color.textFaint }}>Read-only — analyse and plan, never edit files</div>
                            </div>
                            <button
                                type="button"
                                style={toggleStyle(planMode)}
                                onClick={e => e.stopPropagation()}
                                title="Toggle plan mode"
                            >
                                <span style={{
                                    position: 'absolute', top: '3px',
                                    left: planMode ? '17px' : '3px',
                                    width: '12px', height: '12px', borderRadius: '50%',
                                    background: '#fff', transition: 'left 0.15s',
                                }} />
                            </button>
                        </div>

                        {/* Verbose */}
                        <div
                            style={flagRowStyle}
                            onClick={() => setFlag('verbose', !flags.verbose)}
                        >
                            <div>
                                <div style={{ fontSize: '12px', fontWeight: 500, color: color.textSecondary }}>Verbose</div>
                                <div style={{ fontSize: '10px', color: color.textFaint }}>--verbose — detailed claude output</div>
                            </div>
                            <button
                                type="button"
                                style={toggleStyle(!!flags.verbose)}
                                onClick={e => e.stopPropagation()}
                                title="Toggle --verbose"
                            >
                                <span style={{
                                    position: 'absolute', top: '3px',
                                    left: flags.verbose ? '17px' : '3px',
                                    width: '12px', height: '12px', borderRadius: '50%',
                                    background: '#fff', transition: 'left 0.15s',
                                }} />
                            </button>
                        </div>

                        {/* Max Turns */}
                        <div style={{ ...flagRowStyle, gap: '12px' }}>
                            <div style={{ flex: 1 }}>
                                <div style={{ fontSize: '12px', fontWeight: 500, color: color.textSecondary }}>Max Turns</div>
                                <div style={{ fontSize: '10px', color: color.textFaint }}>--max-turns N — limit conversation turns</div>
                            </div>
                            <input
                                type="number"
                                min={1}
                                max={500}
                                placeholder="∞"
                                value={flags.max_turns ?? ''}
                                onChange={e => setFlag('max_turns', e.target.value ? parseInt(e.target.value, 10) : null)}
                                style={{ ...inputStyle, width: '72px', textAlign: 'center', padding: '4px 8px' }}
                            />
                        </div>
                    </div>

                    {/* Footer */}
                    <div style={{ display: 'flex', gap: '8px', justifyContent: 'flex-end', paddingTop: '4px' }}>
                        <button type="button" onClick={onClose} style={cancelBtnStyle}>Cancel</button>
                        <button type="submit" disabled={loading} style={{ ...submitBtnStyle, opacity: loading ? 0.7 : 1 }}>
                            {loading ? 'Saving…' : 'Save Changes'}
                        </button>
                    </div>
                </form>
            </div>
        </div>
    )
}
