// resources/js/pages/Configurations.tsx
import { usePage } from '@inertiajs/react'
import AppLayout from '@/layouts/AppLayout'
import { ProjectLayout } from '@/layouts/ProjectLayout'
import { CommandsPanel } from '@/pages/configurations/index'
import type { Command } from '@/pages/configurations/index'

export type * from '@/pages/configurations/types'

// Project Configurations screen served at "/{project}/configurations" via
// Inertia props. Commands are delivered by configurations_page_controller on
// every visit — no initial client fetch — so the panel can never fail to load.
export default function Configurations() {
    const { props } = usePage<{ project: string; project_id: number | null; commands: Command[] }>()

    if (props.project_id === null) {
        return (
            <div className="flex-1 flex items-center justify-center">
                <span className="text-zinc-400 text-[13px]">Project not found</span>
            </div>
        )
    }

    return (
        <CommandsPanel
            projectId={props.project_id}
            projectSlug={props.project}
            initialCommands={props.commands ?? []}
        />
    )
}

// Nested persistent layouts — see Home.tsx for why both must be listed here.
Configurations.layout = [AppLayout, ProjectLayout]

// resources/js/pages/Configurations.vue
<script setup lang="ts">
import CommandsPanel from '@/pages/configurations/CommandsPanel.vue'
import type { Command } from '@/pages/configurations/types'

// Commands arrive as props on every visit, so the panel never has an initial fetch to fail.
defineProps<{ project: string; project_id: number | null; commands?: Command[] }>()
</script>

<template>
    <div v-if="project_id === null" class="flex-1 flex items-center justify-center">
        <span class="text-zinc-400 text-ui-13">Project not found</span>
    </div>
    <CommandsPanel
        v-else
        :project-id="project_id"
        :project-slug="project"
        :initial-commands="commands ?? []"
    />
</template>
