// resources/js/pages/Tasks.vue
<script setup lang="ts">
import { router, usePage } from '@inertiajs/vue3'
import { computed } from 'vue'
import AppLayout from '@/layouts/AppLayout.vue'
import ProjectLayout from '@/layouts/ProjectLayout.vue'
import type { NewTask } from '@/pages/tasks/CreateTaskModal.vue'
import TasksView from '@/pages/tasks/TasksView.vue'
import useProjects from '@/queries/projectsQuery'
import useWorkspaces from '@/queries/workspacesQuery'
import type { Task } from '@/types/type'

defineOptions({ layout: [AppLayout, ProjectLayout] })

// Tasks arrive as Inertia props (tasks_page_controller); mutations hit the JSON API
// and re-fetch with a partial reload. The props, not queries/taskQuery, are the source:
// the API list is paginated, hides older closed tasks and returns a JSON:API envelope.
const page = usePage<{ project: string; project_id: number | null; tasks?: Task[] }>()
const tasks = computed(() => page.props.tasks ?? [])
const { projects } = useProjects()
const { workspaces } = useWorkspaces()

async function send(url: string, method: 'POST' | 'PATCH' | 'DELETE', body?: object) {
    await fetch(url, {
        method,
        headers: body ? { 'Content-Type': 'application/json' } : undefined,
        body: body ? JSON.stringify(body) : undefined,
    })
    router.reload({ only: ['tasks'] })
}

function createTask({ projectId, ...task }: NewTask) {
    return send(`/api/projects/${projectId}/tasks`, 'POST', task)
}

function updateStatus(task: Task, status: Task['status']) {
    return send(`/api/tasks/${task.id}`, 'PATCH', { status })
}

function deleteTask(task: Task) {
    return send(`/api/tasks/${task.id}`, 'DELETE')
}
</script>

<template>
    <TasksView
        :tasks="tasks"
        :projects="projects"
        :workspaces="workspaces"
        :default-project-id="page.props.project_id"
        @create-task="createTask"
        @update-status="updateStatus"
        @delete-task="deleteTask"
    />
</template>

// resources/js/pages/Tasks.tsx
import { useState } from 'react'
import { router, usePage } from '@inertiajs/react'
import AppLayout from '@/layouts/AppLayout'
import { ProjectLayout } from '@/layouts/ProjectLayout'
import { TasksView } from '@/layouts/views/TasksView'
import { CreateTaskModal } from '@/components/modals/CreateTaskModal'
import { TaskDetailModal } from '@/components/modals/TaskDetailModal'
import useProjects from '@/queries/useProjects'
import useWorkspaces from '@/queries/useWorkspaces'
import type { Task } from '@/types/type'

// Self-contained tasks page. Data is delivered as Inertia props by
// tasks_page_controller on every visit; mutations hit the JSON API directly and
// re-fetch with a partial reload. No task state lives in the layout/context — the
// page owns it. (projects/workspaces are read from context only to seed the
// create-task project picker; they are not task state.)
export default function Tasks() {
    const { props } = usePage<{ project: string; project_id: number | null; tasks: Task[] }>()
    const { workspaces } = useWorkspaces()
    const { projects } = useProjects()

    const tasks = props.tasks ?? []
    const [showCreate, setShowCreate] = useState(false)
    const [selected, setSelected] = useState<Task | null>(null)

    const refresh = () => router.reload({ only: ['tasks'] })

    async function createTask(title: string, body: string, assignees: string[], projectId: number) {
        await fetch(`/api/projects/${projectId}/tasks`, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ title, body, assignees }),
        })
        setShowCreate(false)
        refresh()
    }

    async function updateStatus(task: Task, status: Task['status']) {
        await fetch(`/api/tasks/${task.id}`, {
            method: 'PATCH',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ status }),
        })
        refresh()
    }

    async function deleteTask(task: Task) {
        await fetch(`/api/tasks/${task.id}`, { method: 'DELETE' })
        refresh()
    }

    return (
        <>
            <TasksView
                tasks={tasks}
                onOpenCreateTask={() => setShowCreate(true)}
                onUpdateStatus={updateStatus}
                onDeleteTask={deleteTask}
                onOpenTask={setSelected}
            />

            {selected && (
                <TaskDetailModal task={selected} onClose={() => setSelected(null)} />
            )}

            {showCreate && (
                <CreateTaskModal
                    onClose={() => setShowCreate(false)}
                    onCreated={createTask}
                    projects={projects}
                    workspaces={workspaces}
                    defaultProjectId={props.project_id}
                />
            )}
        </>
    )
}

// Nested persistent layouts — see Home.tsx for why both must be listed here.
Tasks.layout = [AppLayout, ProjectLayout]
