// resources/js/pages/agents/Detail.tsx
import { useCallback, useEffect, useRef } from 'react'
import { ArrowLeft, Image } from 'lucide-react'
import AppLayout from '@/layouts/AppLayout'
import { ProjectLayout } from '@/layouts/ProjectLayout'
import { color } from '@/tokens'
import { AGENT_TYPE_LABELS, AGENT_TYPE_COLORS } from '@/types/agent'
import { agentColor } from '@/utils/agentColor'
import { useAgents } from '@/queries/agents'
import { attachTerminal } from '@/hooks/useTerminalSessions'
import { useAppLayout } from '@/layouts/context/AppLayoutContext'
import { useProjectStore } from '@/stores/projectStore'
import { DotsIndicator } from '@/layouts/sidebar/Project'
import { AgentsListPanel } from './AgentsListPanel'
import { ProjectOverview } from './ProjectOverview'

// ─── Claude status badge ──────────────────────────────────────────────────────

function ClaudeStatusBadge({ status }: { status?: 'running' | 'done' }) {
    if (!status) return null
    if (status === 'running') {
        return (
            <span style={{ display: 'flex', alignItems: 'center', gap: '6px', marginLeft: '8px' }}>
                <DotsIndicator />
                <span style={{ color: color.warning, fontSize: '11px', fontFamily: '"JetBrains Mono", monospace' }}>running</span>
            </span>
        )
    }
    return (
        <span style={{ display: 'flex', alignItems: 'center', gap: '5px', marginLeft: '6px' }}>
            <span style={{ width: '7px', height: '7px', borderRadius: '50%', background: color.success }} />
            <span style={{ color: color.success, fontSize: '11px', fontFamily: '"JetBrains Mono", monospace' }}>done</span>
        </span>
    )
}

// ─── Agent detail page ────────────────────────────────────────────────────────
// Served at /{project}/agents/{id}. Owns the agent-execution chrome (agents list,
// header, image-drop) and a terminal SLOT. The xterm instances + WebSockets stay
// owned by AppLayout/AppLayoutContext; on mount this page re-parents the active
// agent's live term into its slot, and on unmount parks it back in the persistent
// holder (AgentsIndex) — the WebSocket is never closed, so PTY sessions survive.

export default function AgentDetail() {
    const {
        activeAgentId,
        setActiveAgentId,
        agentSessions,
        agentContainerRefs,
        agentTerminalSlot,
        launchAgentSession,
        isDraggingOver,
        setIsDraggingOver,
        uploadImage,
        fileInputRef,
        claudeStatus,
    } = useAppLayout()
    const activeProject = useProjectStore(s => s.activeProject)

    const { agents: projectAgents } = useAgents(activeProject?.id ?? null)

    const activeAgent = activeAgentId !== null
        ? projectAgents.find(a => a.id === activeAgentId) ?? null
        : null
    const agentBg = activeAgent
        ? (AGENT_TYPE_COLORS[activeAgent.agent_type] ?? color.accent)
        : (activeProject ? agentColor(activeProject.name) : color.accent)
    const displayName = activeAgent ? activeAgent.name : (activeProject?.name ?? '')

    // Register the slot node so launchAgentSession attaches new terms here directly.
    const slotRef = useRef<HTMLDivElement | null>(null)
    const setSlot = useCallback((node: HTMLDivElement | null) => {
        slotRef.current = node
        agentTerminalSlot.current = node
    }, [agentTerminalSlot])

    // Re-parent the active agent's live term into the slot; park it back on unmount
    // or when switching agents. Never closes the WS — only moves the xterm DOM.
    useEffect(() => {
        const slot = slotRef.current
        if (activeAgentId === null || !slot) return
        const sess = agentSessions.current.get(activeAgentId)
        if (sess) {
            // Move the live terminal into the visible slot. term.open() can't
            // re-parent an already-open terminal, so attachTerminal relocates its
            // root element when the session already exists (e.g. it was launched
            // into the off-screen holder during the navigation transition).
            attachTerminal(sess.term, slot)
            sess.observer.disconnect()
            sess.observer.observe(slot)
            sess.fitAddon.fit()
            sess.term.focus()
        } else {
            // No session yet. The context "start all agents" effect fires during the
            // Inertia navigation transition — before this slot is registered — so it
            // can attach to the off-screen holder or no-op and never retry. Now that
            // the slot is mounted, establish the active agent's session directly in
            // it. launchAgentSession is idempotent, so this can't open a second PTY.
            launchAgentSession(activeAgentId, true)
        }
        const parkedId = activeAgentId
        return () => {
            // Park the terminal back in its off-screen holder before the slot
            // unmounts. Without this the terminal's DOM dies with the slot and the
            // surviving session has no element to re-attach on return — a blank page.
            const s = agentSessions.current.get(parkedId)
            const holder = agentContainerRefs.current.get(parkedId)
            if (s && holder) {
                attachTerminal(s.term, holder)
                // Stop observing the visible slot; the (possibly hidden) holder
                // isn't observed — a refit runs when the term re-attaches to a slot.
                s.observer.disconnect()
            }
        }
    }, [activeAgentId, agentSessions, agentContainerRefs])

    if (!activeProject) return null

    // Back / no-selection: render the overview in place. Navigating to /{slug}
    // would 302 to the default agent and bounce straight back here, so the page
    // owns the overview too (the URL stays on the agent route — harmless).
    if (activeAgentId === null) return <ProjectOverview project={activeProject} />

    return (
        <div style={{ flex: 1, overflow: 'hidden', display: 'flex' }}>
            {/* Agents list — left */}
            <AgentsListPanel project={activeProject} />

            {/* Agent execution — chrome + terminal slot */}
            <div
                style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', position: 'relative', background: '#fff' }}
                onDragOver={e => { e.preventDefault(); setIsDraggingOver(true) }}
                onDragEnter={e => { e.preventDefault(); setIsDraggingOver(true) }}
                onDragLeave={e => { if (!e.currentTarget.contains(e.relatedTarget as Node)) setIsDraggingOver(false) }}
                onDrop={e => {
                    e.preventDefault()
                    setIsDraggingOver(false)
                    const file = e.dataTransfer.files[0]
                    if (file) uploadImage(file)
                }}
            >
                {/* Header */}
                <div style={{
                    height: '48px', flexShrink: 0, display: 'flex', alignItems: 'center',
                    paddingLeft: '16px', paddingRight: '14px', gap: '10px',
                    borderBottom: `1px solid ${color.stroke}`, background: '#fff',
                }}>
                    <button
                        onClick={() => setActiveAgentId(null)}
                        title="Back"
                        style={{
                            background: 'transparent', border: 'none', color: color.textFaint, cursor: 'pointer',
                            padding: '4px', display: 'flex', alignItems: 'center', borderRadius: '4px',
                        }}
                        onMouseEnter={e => { e.currentTarget.style.color = color.textPrimary; e.currentTarget.style.background = color.bgCanvas }}
                        onMouseLeave={e => { e.currentTarget.style.color = color.textFaint; e.currentTarget.style.background = 'transparent' }}
                    >
                        <ArrowLeft size={14}/>
                    </button>

                    <div style={{
                        width: '28px', height: '28px', borderRadius: '8px', flexShrink: 0, background: agentBg,
                        display: 'flex', alignItems: 'center', justifyContent: 'center',
                        fontSize: '11px', fontWeight: 700, color: '#fff',
                    }}>
                        {displayName.charAt(0).toUpperCase()}
                    </div>

                    <div style={{ flex: 1, minWidth: 0, display: 'flex', alignItems: 'center', gap: '8px' }}>
                        <span style={{ color: color.textPrimary, fontSize: '13px', fontWeight: 600, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
                            {displayName}
                        </span>
                        <span style={{
                            fontSize: '10px', fontWeight: 600, padding: '2px 7px', borderRadius: '10px', letterSpacing: '0.04em',
                            background: `${agentBg}18`, border: `1px solid ${agentBg}40`, color: agentBg, flexShrink: 0,
                        }}>
                            {activeAgent ? (AGENT_TYPE_LABELS[activeAgent.agent_type] ?? activeAgent.agent_type).toUpperCase() : 'AGENT'}
                        </span>
                    </div>

                    <div style={{ display: 'flex', alignItems: 'center', gap: '8px', flexShrink: 0 }}>
                        <ClaudeStatusBadge status={claudeStatus[activeProject.id]} />
                    </div>
                </div>

                {/* Drag overlay */}
                {isDraggingOver && (
                    <div style={{
                        position: 'absolute', inset: 0, zIndex: 10, background: color.accentGlow,
                        border: `2px dashed ${color.accent}`, borderRadius: '4px',
                        display: 'flex', alignItems: 'center', justifyContent: 'center', pointerEvents: 'none',
                    }}>
                        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px' }}>
                            <Image size={36} color={color.accent} opacity={0.8}/>
                            <span style={{ color: color.accent, fontSize: '13px', fontFamily: '"JetBrains Mono", monospace' }}>
                                Drop image to attach
                            </span>
                        </div>
                    </div>
                )}

                {/* Hidden file input for image uploads */}
                <input
                    ref={fileInputRef}
                    type="file"
                    accept="image/*"
                    style={{ display: 'none' }}
                    onChange={e => {
                        const file = e.target.files?.[0]
                        if (file) uploadImage(file)
                        e.target.value = ''
                    }}
                />

                {/* Terminal slot — the active agent's live xterm is re-parented here */}
                <div ref={setSlot} style={{ flex: 1, position: 'relative', overflow: 'hidden', padding: '8px', boxSizing: 'border-box' }} />
            </div>
        </div>
    )
}

// Nested persistent layouts — same refs as Home/Tasks so Inertia preserves them
// (and the terminal holder in AppLayout/AgentsIndex) across navigation.
AgentDetail.layout = [AppLayout, ProjectLayout]

// resources/js/pages/agents/Detail.vue
<script setup lang="ts">
import { storeToRefs } from 'pinia'
import { computed, ref, watch } from 'vue'
import DotsIndicator from '@/components/ui/DotsIndicator.vue'
import Icon from '@/components/ui/Icon.vue'
import { attachTerminal } from '@/composables/useTerminalSessions'
import { useAppLayoutStore } from '@/stores/appLayoutStore'
import { useProjectStore } from '@/stores/projectStore'
import { color } from '@/tokens'
import { AGENT_TYPE_COLORS, AGENT_TYPE_LABELS } from '@/types/agent'
import { agentColor } from '@/utils/agentColor'
import AgentsListPanel from './AgentsListPanel.vue'
import PmCheckinControl from './PmCheckinControl.vue'
import ProjectOverview from './ProjectOverview.vue'
import { agentRoleLabel } from './presentation'

// Served at /{project}/agents/{id}. Owns the agent-execution chrome (agents
// list, header, image drop) and a terminal slot. The xterm instances and their
// sockets stay owned by the app layout store: the active agent's live terminal
// is moved into the slot, and parked back in the layout's off-screen holder
// when the agent changes or the page unmounts, so the PTY never closes.

const layout = useAppLayoutStore()
const { activeAgentId, isDraggingOver, claudeStatus } = storeToRefs(layout)
const { activeProject } = storeToRefs(useProjectStore())

const activeAgent = computed(() =>
    layout.agentHook.agents.value.find(a => a.id === activeAgentId.value) ?? null,
)
const agentBg = computed(() => {
    if (activeAgent.value) return AGENT_TYPE_COLORS[activeAgent.value.agent_type] ?? color.accent
    return activeProject.value ? agentColor(activeProject.value.name) : color.accent
})
const displayName = computed(() => activeAgent.value?.name ?? activeProject.value?.name ?? '')
const typeLabel = computed(() => {
    const agent = activeAgent.value
    return agent ? (AGENT_TYPE_LABELS[agent.agent_type] ?? agent.agent_type).toUpperCase() : 'AGENT'
})
const subtitle = computed(() => {
    const agent = activeAgent.value
    if (!agent) return null
    return agent.model ? `${agentRoleLabel(agent)} · ${agent.model}` : agentRoleLabel(agent)
})
const status = computed(() => (activeProject.value ? claudeStatus.value[activeProject.value.id] : undefined))

const terminalSlot = ref<HTMLElement | null>(null)

function showAgentTerminal(agentId: number, el: HTMLElement) {
    layout.setAgentContainer(agentId, el)
    const session = layout.agentSessions.get(agentId)
    if (!session) {
        // launchAgentSession opens into the registered container, now this slot;
        // it is idempotent, so the store's own launch can't open a second PTY.
        layout.launchAgentSession(agentId, true)
        return
    }
    attachTerminal(session.term, el)
    session.observer.disconnect()
    session.observer.observe(el)
    requestAnimationFrame(() => { session.fitAddon.fit(); session.term.focus() })
}

function parkAgentTerminal(agentId: number) {
    const holder = layout.terminalHolder
    if (!holder) return
    layout.setAgentContainer(agentId, holder)
    const session = layout.agentSessions.get(agentId)
    if (!session) return
    // The holder is not observed; the terminal refits when it is next shown in a slot.
    session.observer.disconnect()
    attachTerminal(session.term, holder)
}

watch(
    [activeAgentId, terminalSlot],
    ([agentId, el], _previous, onCleanup) => {
        if (agentId === null || !el) return
        showAgentTerminal(agentId, el)
        onCleanup(() => parkAgentTerminal(agentId))
    },
    { flush: 'post', immediate: true },
)

function onDragLeave(e: DragEvent) {
    const target = e.currentTarget as HTMLElement
    if (!target.contains(e.relatedTarget as Node | null)) isDraggingOver.value = false
}

function onDrop(e: DragEvent) {
    isDraggingOver.value = false
    const file = e.dataTransfer?.files[0]
    if (file) layout.uploadImage(file)
}
</script>

<template>
    <template v-if="activeProject">
        <!-- Back / no selection renders the overview in place: visiting /{slug}
             would redirect to the default agent and bounce straight back here. -->
        <ProjectOverview v-if="activeAgentId === null" :project="activeProject" />

        <div v-else class="flex-1 overflow-hidden flex">
            <AgentsListPanel :project="activeProject" />

            <div
                data-testid="agent-execution"
                class="flex-1 flex flex-col overflow-hidden relative bg-white"
                @dragover.prevent="isDraggingOver = true"
                @dragenter.prevent="isDraggingOver = true"
                @dragleave="onDragLeave"
                @drop.prevent="onDrop"
            >
                <div class="min-h-[48px] shrink-0 flex items-center pl-4 pr-3.5 pt-[7px] pb-[7px] gap-2.5 border-b border-stroke bg-white">
                    <button
                        title="Back"
                        class="bg-transparent border-0 text-zinc-400 cursor-pointer p-1 flex items-center rounded-sm hover:text-zinc-900 hover:bg-canvas"
                        @click="layout.setActiveAgentId(null)"
                    >
                        <Icon name="arrow-left" :size="14" />
                    </button>

                    <div
                        class="w-7 h-7 rounded-md shrink-0 flex items-center justify-center text-[11px] font-bold text-white"
                        :style="{ background: agentBg }"
                    >
                        {{ displayName.charAt(0).toUpperCase() }}
                    </div>

                    <div class="flex-1 min-w-0 flex flex-col justify-center gap-px">
                        <div class="flex items-center gap-2">
                            <span class="text-zinc-900 text-[13px] font-semibold truncate">{{ displayName }}</span>
                            <span
                                class="text-[10px] font-semibold py-0.5 px-[7px] rounded-lg tracking-[0.04em] border shrink-0"
                                :style="{ background: `${agentBg}18`, borderColor: `${agentBg}40`, color: agentBg }"
                            >
                                {{ typeLabel }}
                            </span>
                        </div>
                        <span v-if="subtitle" class="text-zinc-500 text-[12px] truncate">{{ subtitle }}</span>
                    </div>

                    <div class="flex items-center gap-3 shrink-0">
                        <PmCheckinControl v-if="activeAgent?.agent_type === 'pm'" :agent-id="activeAgent.id" compact />
                        <span v-if="status === 'running'" class="flex items-center gap-1.5 ml-2">
                            <DotsIndicator />
                            <span class="text-amber-700 text-[11px] font-mono">running</span>
                        </span>
                        <span v-else-if="status === 'done'" class="flex items-center gap-[5px] ml-1.5">
                            <span class="w-[7px] h-[7px] rounded-full bg-success" />
                            <span class="text-success text-[11px] font-mono">done</span>
                        </span>
                    </div>
                </div>

                <div
                    v-if="isDraggingOver"
                    class="absolute inset-0 z-10 bg-[rgba(9,105,218,0.08)] border-2 border-dashed border-accent rounded-sm flex items-center justify-center pointer-events-none"
                >
                    <div class="flex flex-col items-center gap-2.5">
                        <Icon name="image" :size="36" :color="color.accent" class="opacity-80" />
                        <span class="text-accent text-[13px] font-mono">Drop image to attach</span>
                    </div>
                </div>

                <div ref="terminalSlot" data-testid="agent-terminal" class="flex-1 relative overflow-hidden bg-canvas p-2 box-border" />
            </div>
        </div>
    </template>
</template>
