// resources/js/pages/tasks/CreateTaskModal.vue
<script setup lang="ts">
import { computed, ref, type Directive } from 'vue'
import Modal from '@/components/ui/Modal.vue'
import TagInput from '@/components/ui/TagInput.vue'
import { cancelBtnClass, inputClass, labelClass, submitBtnClass } from '@/components/ui/styles'
import type { Project, Workspace } from '@/types/type'

export type NewTask = { title: string; body: string; assignees: string[]; projectId: number }

const LS_TASK_PROJECT_ID = 'keera:task_project_id'
const LS_TASK_WORKSPACE_ID = 'keera:task_workspace_id'

const props = defineProps<{
    projects: Project[]
    workspaces: Workspace[]
    defaultProjectId: number | null
}>()

const emit = defineEmits<{ created: [task: NewTask] }>()

defineSlots<{ trigger(): unknown }>()

// Read on every open rather than cached in a ref: the board renders one modal per
// "new task" trigger, and each must see the picker choice the other one saved.
function readStoredId(key: string): number | null {
    try {
        const stored = localStorage.getItem(key)
        return stored === null ? null : parseInt(stored, 10)
    } catch {
        return null
    }
}

function storeId(key: string, id: number | null) {
    try {
        if (id === null) localStorage.removeItem(key)
        else localStorage.setItem(key, String(id))
    } catch {
        // Storage unavailable: the picker just won't be remembered.
    }
}

const title = ref('')
const body = ref('')
const assignees = ref<string[]>([])
const error = ref('')
const selectedWorkspaceId = ref<number | null>(null)
const selectedProjectId = ref<number | null>(null)

function initialWorkspaceId(): number | null {
    const stored = readStoredId(LS_TASK_WORKSPACE_ID)
    if (stored !== null && props.workspaces.some(w => w.id === stored)) return stored
    return props.projects.find(p => p.id === props.defaultProjectId)?.workspace_id ?? null
}

function initialProjectId(): number | null {
    const stored = readStoredId(LS_TASK_PROJECT_ID)
    if (stored !== null && props.projects.some(p => p.id === stored)) return stored
    return props.defaultProjectId
}

function onOpenChange(open: boolean) {
    if (!open) return
    title.value = ''
    body.value = ''
    assignees.value = []
    error.value = ''
    selectedWorkspaceId.value = initialWorkspaceId()
    selectedProjectId.value = initialProjectId()
}

const visibleProjects = computed(() =>
    selectedWorkspaceId.value !== null
        ? props.projects.filter(p => p.workspace_id === selectedWorkspaceId.value)
        : props.projects,
)

function onWorkspaceChange(event: Event) {
    const value = (event.target as HTMLSelectElement).value
    const id = value === '' ? null : parseInt(value, 10)
    selectedWorkspaceId.value = id
    storeId(LS_TASK_WORKSPACE_ID, id)
    const first = id !== null ? props.projects.find(p => p.workspace_id === id) : props.projects[0]
    selectedProjectId.value = first?.id ?? null
    storeId(LS_TASK_PROJECT_ID, selectedProjectId.value)
}

function onProjectChange(event: Event) {
    const id = parseInt((event.target as HTMLSelectElement).value, 10)
    selectedProjectId.value = id
    storeId(LS_TASK_PROJECT_ID, id)
}

function submit(close: () => void) {
    if (!title.value.trim()) { error.value = 'Title is required'; return }
    if (!selectedProjectId.value) { error.value = 'Select a project'; return }
    emit('created', {
        title: title.value.trim(),
        body: body.value.trim(),
        assignees: assignees.value,
        projectId: selectedProjectId.value,
    })
    close()
}

// `autofocus` is ignored on elements inserted after page load, and the form mounts on open.
const vFocus: Directive<HTMLElement> = { mounted: el => el.focus() }

// A literal hex, not a token: TagInput appends alpha suffixes, which a var() cannot take.
const ASSIGNEE_COLOR = '#2563eb'

const selectClass = `${inputClass} w-full box-border cursor-pointer`
</script>

<template>
    <Modal
        aria-label="New task"
        panel-class="bg-modal border border-stroke rounded-md p-6 w-[420px] flex flex-col gap-4"
        @open-change="onOpenChange"
    >
        <template #trigger>
            <slot name="trigger" />
        </template>

        <template #default="{ close }">
            <h2 class="m-0 text-zinc-900 text-[15px] font-semibold">New Task</h2>

            <span v-if="error" role="alert" class="text-danger text-[12px]">{{ error }}</span>

            <form class="flex flex-col gap-3.5" @submit.prevent="submit(close)">
                <div class="flex gap-2">
                    <label v-if="workspaces.length > 0" class="flex flex-col gap-1 flex-1">
                        <span :class="labelClass">Workspace</span>
                        <select
                            name="workspace"
                            :value="selectedWorkspaceId ?? ''"
                            :class="selectClass"
                            @change="onWorkspaceChange"
                        >
                            <option value="">All</option>
                            <option v-for="w in workspaces" :key="w.id" :value="w.id">{{ w.name }}</option>
                        </select>
                    </label>
                    <label class="flex flex-col gap-1 flex-1">
                        <span :class="labelClass">Project <span class="text-danger">*</span></span>
                        <select
                            name="project"
                            :value="selectedProjectId ?? ''"
                            :class="selectClass"
                            @change="onProjectChange"
                        >
                            <option value="" disabled>Select project</option>
                            <option v-for="p in visibleProjects" :key="p.id" :value="p.id">{{ p.name }}</option>
                        </select>
                    </label>
                </div>

                <label class="flex flex-col gap-1">
                    <span :class="labelClass">Title <span class="text-danger">*</span></span>
                    <input
                        v-model="title"
                        v-focus
                        name="title"
                        placeholder="Task title"
                        :class="[inputClass, 'w-full box-border']"
                        @input="error = ''"
                    >
                </label>

                <label class="flex flex-col gap-1">
                    <span :class="labelClass">Description</span>
                    <textarea
                        v-model="body"
                        name="body"
                        placeholder="Optional details…"
                        rows="3"
                        :class="[inputClass, 'w-full box-border resize-y leading-normal']"
                    />
                </label>

                <div class="flex flex-col gap-1.5">
                    <span :class="labelClass">Assignees</span>
                    <TagInput v-model="assignees" placeholder="Add name and press Enter" :tag-color="ASSIGNEE_COLOR" />
                </div>

                <div class="flex gap-2 justify-end pt-1">
                    <button type="button" :class="cancelBtnClass" @click="close">Cancel</button>
                    <button type="submit" :class="submitBtnClass">Create Task</button>
                </div>
            </form>
        </template>
    </Modal>
</template>

// resources/js/components/modals/CreateTaskModal.tsx
import { useState } from 'react'
import type { Project, Workspace } from '@/types/type'
import { labelClass, inputClass, cancelBtnClass, submitBtnClass } from '@/components/ui/styles'

const LS_TASK_PROJECT_ID = 'keera:task_project_id'
const LS_TASK_WORKSPACE_ID = 'keera:task_workspace_id'

export function CreateTaskModal({
    onClose,
    onCreated,
    projects,
    workspaces,
    defaultProjectId,
}: {
    onClose: () => void
    onCreated: (title: string, body: string, assignees: string[], projectId: number) => void
    projects: Project[]
    workspaces: Workspace[]
    defaultProjectId: number | null
}) {
    const [title, setTitle] = useState('')
    const [body, setBody] = useState('')
    const [assigneeInput, setAssigneeInput] = useState('')
    const [assignees, setAssignees] = useState<string[]>([])
    const [error, setError] = useState('')

    const initWorkspaceId = (): number | null => {
        const stored = localStorage.getItem(LS_TASK_WORKSPACE_ID)
        if (stored !== null) {
            const id = parseInt(stored, 10)
            if (workspaces.some(w => w.id === id)) return id
        }
        const proj = projects.find(p => p.id === defaultProjectId)
        return proj?.workspace_id ?? null
    }
    const initProjectId = (): number | null => {
        const stored = localStorage.getItem(LS_TASK_PROJECT_ID)
        if (stored !== null) {
            const id = parseInt(stored, 10)
            if (projects.some(p => p.id === id)) return id
        }
        return defaultProjectId
    }

    const [selectedWorkspaceId, setSelectedWorkspaceId] = useState<number | null>(initWorkspaceId)
    const [selectedProjectId, setSelectedProjectId] = useState<number | null>(initProjectId)

    const visibleProjects = selectedWorkspaceId !== null
        ? projects.filter(p => p.workspace_id === selectedWorkspaceId)
        : projects

    function handleWorkspaceChange(id: number | null) {
        setSelectedWorkspaceId(id)
        if (id !== null) localStorage.setItem(LS_TASK_WORKSPACE_ID, String(id))
        else localStorage.removeItem(LS_TASK_WORKSPACE_ID)
        const first = id !== null ? projects.find(p => p.workspace_id === id) : projects[0]
        const newProjectId = first?.id ?? null
        setSelectedProjectId(newProjectId)
        if (newProjectId !== null) localStorage.setItem(LS_TASK_PROJECT_ID, String(newProjectId))
        else localStorage.removeItem(LS_TASK_PROJECT_ID)
    }

    function handleProjectChange(id: number) {
        setSelectedProjectId(id)
        localStorage.setItem(LS_TASK_PROJECT_ID, String(id))
    }

    function addAssignee() {
        const name = assigneeInput.trim()
        if (!name || assignees.includes(name)) return
        setAssignees(prev => [...prev, name])
        setAssigneeInput('')
    }

    function removeAssignee(name: string) {
        setAssignees(prev => prev.filter(a => a !== name))
    }

    function handleSubmit(e: React.FormEvent) {
        e.preventDefault()
        if (!title.trim()) { setError('Title is required'); return }
        if (!selectedProjectId) { setError('Select a project'); return }
        onCreated(title.trim(), body.trim(), assignees, selectedProjectId)
        onClose()
    }

    const selectClass = `${inputClass} w-full box-border cursor-pointer`

    return (
        <div className="fixed inset-0 bg-black/50 flex items-center justify-center z-[100]">
            <div className="bg-modal border border-stroke rounded-md p-6 w-[420px] flex flex-col gap-4">
                <h2 className="m-0 text-zinc-900 text-[15px] font-semibold">New Task</h2>

                {error && <span className="text-danger text-[12px]">{error}</span>}

                <form onSubmit={handleSubmit} className="flex flex-col gap-3.5">
                    {/* Workspace + Project row */}
                    <div className="flex gap-2">
                        {workspaces.length > 0 && (
                            <label className="flex flex-col gap-1 flex-1">
                                <span className={labelClass}>Workspace</span>
                                <select
                                    value={selectedWorkspaceId ?? ''}
                                    onChange={e => handleWorkspaceChange(e.target.value === '' ? null : parseInt(e.target.value, 10))}
                                    className={selectClass}
                                >
                                    <option value="">All</option>
                                    {workspaces.map(w => (
                                        <option key={w.id} value={w.id}>{w.name}</option>
                                    ))}
                                </select>
                            </label>
                        )}
                        <label className="flex flex-col gap-1 flex-1">
                            <span className={labelClass}>Project <span className="text-danger">*</span></span>
                            <select
                                value={selectedProjectId ?? ''}
                                onChange={e => handleProjectChange(parseInt(e.target.value, 10))}
                                className={selectClass}
                            >
                                <option value="" disabled>Select project</option>
                                {visibleProjects.map(p => (
                                    <option key={p.id} value={p.id}>{p.name}</option>
                                ))}
                            </select>
                        </label>
                    </div>

                    {/* Title */}
                    <label className="flex flex-col gap-1">
                        <span className={labelClass}>Title <span className="text-danger">*</span></span>
                        <input
                            autoFocus
                            value={title}
                            onChange={e => { setTitle(e.target.value); setError('') }}
                            placeholder="Task title"
                            className={`${inputClass} w-full box-border`}
                        />
                    </label>

                    {/* Description / body */}
                    <label className="flex flex-col gap-1">
                        <span className={labelClass}>Description</span>
                        <textarea
                            value={body}
                            onChange={e => setBody(e.target.value)}
                            placeholder="Optional details…"
                            rows={3}
                            className={`${inputClass} w-full box-border resize-y leading-normal`}
                        />
                    </label>

                    {/* Assignees */}
                    <div className="flex flex-col gap-1.5">
                        <span className={labelClass}>Assignees</span>
                        {assignees.length > 0 && (
                            <div className="flex flex-wrap gap-1.5">
                                {assignees.map(a => (
                                    <span key={a} className="inline-flex items-center gap-1 bg-blue-50 border border-blue-600 rounded-xl py-0.5 px-2 text-blue-600 text-[11px]">
                                        {a}
                                        <button
                                            type="button"
                                            onClick={() => removeAssignee(a)}
                                            className="bg-transparent border-none text-blue-600 cursor-pointer p-0 leading-none text-[13px]"
                                        >×</button>
                                    </span>
                                ))}
                            </div>
                        )}
                        <div className="flex gap-1.5">
                            <input
                                value={assigneeInput}
                                onChange={e => setAssigneeInput(e.target.value)}
                                onKeyDown={e => {
                                    if (e.key === 'Enter') { e.preventDefault(); addAssignee() }
                                }}
                                placeholder="Add name and press Enter"
                                className={`${inputClass} flex-1 box-border`}
                            />
                            <button
                                type="button"
                                onClick={addAssignee}
                                className="bg-transparent border border-stroke rounded text-zinc-500 text-[12px] py-1.5 px-2.5 cursor-pointer"
                            >Add</button>
                        </div>
                    </div>

                    <div className="flex gap-2 justify-end pt-1">
                        <button type="button" onClick={onClose} className={cancelBtnClass}>Cancel</button>
                        <button type="submit" className={submitBtnClass}>Create Task</button>
                    </div>
                </form>
            </div>
        </div>
    )
}
