// resources/js/layouts/ProjectLayout.tsx
import React from 'react'
import { router, usePage } from '@inertiajs/react'
import { useAppLayout } from './context/AppLayoutContext'
import AgentsIndex from '@/pages/agents/Index'
import { color } from '@/tokens'
import type { ProjectView } from './sidebar/Sidebar'
import { DotsIndicator } from './sidebar/Project'
import { useProjectStore } from '@/stores/projectStore'
import useProjects from '@/queries/useProjects'

// ─── Claude status badge ───────────────────────────────────────────────────────

function ClaudeStatusBadge({ status }: { status?: 'running' | 'done' }) {
    if (!status) return null
    if (status === 'running') {
        return (
            <span style={{ display: 'flex', alignItems: 'center', gap: '6px', marginLeft: '8px' }}>
                <DotsIndicator />
                <span style={{ color: color.warning, fontSize: '11px', fontFamily: '"JetBrains Mono", monospace' }}>running</span>
            </span>
        )
    }
    return (
        <span style={{ display: 'flex', alignItems: 'center', gap: '5px', marginLeft: '6px' }}>
            <span style={{ width: '7px', height: '7px', borderRadius: '50%', background: color.success }} />
            <span style={{ color: color.success, fontSize: '11px', fontFamily: '"JetBrains Mono", monospace' }}>done</span>
        </span>
    )
}

// ─── Project-specific inner layout ────────────────────────────────────────────

export function ProjectLayout({ children }: { children: React.ReactNode }) {
    const {
        claudeStatus,
        projectView, setProjectView,
        sessions, agentSessions,
    } = useAppLayout()

    const { component, props } = usePage<{ project?: string }>()

    // ProjectLayout is the only layout with a project route to read, so it's
    // the one place that resolves the slug into an active project — calling
    // setActiveProject synchronously during render (not in a useEffect) so the
    // store is already fresh by the time the selector below reads it back in
    // this same render pass. Pages using AppLayout without ProjectLayout
    // (Dashboard, Settings, Broadcasting) aren't project-scoped and don't touch
    // this at all — the store just keeps whatever project was last resolved here.
    const { setActiveProject } = useProjects()
    setActiveProject(props.project)
    const activeProject = useProjectStore(s => s.activeProject)

    // Live PTY sessions across all projects (PM + agent terminals).
    const runningCount = sessions.current.size + agentSessions.current.size

    const isTasksPage = component === 'Tasks'
    const isConfigPage = component === 'Configurations'
    // The agent detail page owns the visible agent view; AgentsIndex then only
    // acts as the hidden terminal holder, so hide its wrapper (keep it mounted).
    const isAgentDetail = component === 'agents/Detail'
    const activeView: ProjectView = isTasksPage ? 'tasks' : isConfigPage ? 'commands' : projectView

    return (
        <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>

            {/* ── Nav tabs: Dashboard / Configurations / Tasks + Claude status badge ── */}
            <div className="flex items-stretch px-2 bg-white shrink-0" style={{ borderBottom: `1px solid ${color.stroke}`, height: '40px' }}>
                {([
                    { id: 'agents' as ProjectView, label: 'Dashboard' },
                    { id: 'commands' as ProjectView, label: 'Configurations' },
                    { id: 'tasks' as ProjectView, label: 'Tasks' },
                ] as const).map(tab => {
                    const isActive = activeView === tab.id
                    return (
                        <button
                            key={tab.id}
                            onClick={() => {
                                if (!activeProject) { setProjectView(tab.id); return }
                                if (tab.id === 'tasks') { router.visit(`/${activeProject.slug}/tasks`); return }
                                if (tab.id === 'commands') { router.visit(`/${activeProject.slug}/configurations`); return }
                                setProjectView('agents')
                                if (isTasksPage || isConfigPage) router.visit(`/${activeProject.slug}`)
                            }}
                            className="bg-transparent border-none cursor-pointer px-4 h-full text-[13px] transition-colors duration-100 relative"
                            style={{
                                color: isActive ? color.textPrimary : color.textMuted,
                                fontWeight: isActive ? 600 : 400,
                                borderBottom: isActive ? `2px solid ${color.accent}` : '2px solid transparent',
                                marginBottom: '-1px',
                            }}
                        >
                            {tab.label}
                        </button>
                    )
                })}
                {activeProject && (
                    <>
                        <div className="my-2 mx-1" style={{ width: '1px', background: color.stroke }} />
                        <div className="flex items-center gap-1.5 px-2">
                            <ClaudeStatusBadge status={claudeStatus[activeProject.id]} />
                        </div>
                    </>
                )}

                {/* Global running indicator — far right */}
                {runningCount > 0 && (
                    <div className="flex items-center gap-2 pr-3" style={{ marginLeft: 'auto' }}>
                        <DotsIndicator />
                        <span style={{ color: color.warningBright, fontSize: '12.5px', fontWeight: 600, fontFamily: '"JetBrains Mono", monospace' }}>
                            {runningCount} running
                        </span>
                    </div>
                )}
            </div>

            {/* ── Main content area: routes between views ── */}
            <div style={{ flex: 1, display: 'flex', overflow: 'hidden' }}>

                {/* Agents view — always rendered to keep terminal sessions alive.
                    The wrapper stays mounted (display-toggled) so terminals never
                    unmount and blank out. It shows the overview when no agent is
                    drilled in; on the agent detail page it's hidden and only holds
                    the parked terminal containers (the page renders the live view). */}
                <div style={{ flex: 1, overflow: 'hidden', display: activeView === 'agents' && !isAgentDetail ? 'flex' : 'none' }}>
                    <AgentsIndex />
                </div>

                {/* The Commands (Configurations) and Tasks views are rendered by their
                    own Inertia pages (pages/Configurations.tsx, pages/Tasks.tsx) and
                    delivered here through {children}. */}

                {/* Empty state when no project is selected */}
                {!activeProject && (
                    <div style={{
                        flex: 1, display: 'flex', alignItems: 'center', justifyContent: 'center',
                    }}>
                        <span style={{ color: color.textFaint, fontSize: '13px' }}>No project selected</span>
                    </div>
                )}

                {/* Page-supplied content (for pages that render their own children) */}
                {children}
            </div>

        </div>
    )
}

// resources/js/layouts/ProjectLayout.vue
<script setup lang="ts">
import { router, usePage } from '@inertiajs/vue3'
import { storeToRefs } from 'pinia'
import { computed, onBeforeUnmount, ref, watch, watchEffect } from 'vue'
import DotsIndicator from '@/components/ui/DotsIndicator.vue'
import useProjects from '@/queries/projectsQuery'
import { useAppLayoutStore, type ProjectView } from '@/stores/appLayoutStore'
import { useProjectStore } from '@/stores/projectStore'
import AgentsIndex from '@/pages/agents/Index.vue'

const TABS: { id: ProjectView; label: string }[] = [
    { id: 'agents', label: 'Dashboard' },
    { id: 'commands', label: 'Configurations' },
    { id: 'tasks', label: 'Tasks' },
]

const page = usePage<{ project?: string }>()
const layout = useAppLayoutStore()
const { claudeStatus, projectView, liveSessionCount, activeAgentId } = storeToRefs(layout)
const { activeProject } = storeToRefs(useProjectStore())

// The only layout with a project route, so it is the one place that resolves
// the slug into the active project. Unscoped pages keep the last one resolved.
const { setActiveProject } = useProjects()
watchEffect(() => setActiveProject(page.props.project))

const isTasksPage = computed(() => page.component === 'Tasks')
const isConfigPage = computed(() => page.component === 'Configurations')
const activeView = computed<ProjectView>(() =>
    isTasksPage.value ? 'tasks' : isConfigPage.value ? 'commands' : projectView.value,
)
const activeStatus = computed(() => (activeProject.value ? claudeStatus.value[activeProject.value.id] : undefined))
const showAgentsView = computed(() => !!activeProject.value && activeView.value === 'agents')
// The Dashboard view shows the project overview until an agent is drilled into.
// agents/Detail is not ported yet, so a drilled-in agent shows the PM terminal meanwhile.
const showOverview = computed(() => showAgentsView.value && activeAgentId.value === null)
const showPmTerminal = computed(() => showAgentsView.value && activeAgentId.value !== null)

function selectTab(view: ProjectView) {
    const project = activeProject.value
    if (!project) { projectView.value = view; return }
    if (view === 'tasks') { router.visit(`/${project.slug}/tasks`); return }
    if (view === 'commands') { router.visit(`/${project.slug}/configurations`); return }
    projectView.value = 'agents'
    layout.setActiveAgentId(null)
    if (isTasksPage.value || isConfigPage.value) router.visit(`/${project.slug}`)
}

// The active project's PM terminal is shown here; on a project switch or when
// this layout unmounts it is parked off-screen so its xterm DOM and socket survive.
const terminalSlot = ref<HTMLElement | null>(null)

watch(
    [() => activeProject.value?.id, terminalSlot],
    ([projectId, slot], previous) => {
        const previousId = previous?.[0]
        if (previousId !== undefined && previousId !== projectId) layout.parkPmTerminal(previousId)
        if (projectId !== undefined && slot) layout.showPmTerminal(projectId, slot)
    },
    { flush: 'post', immediate: true },
)

onBeforeUnmount(() => {
    if (activeProject.value) layout.parkPmTerminal(activeProject.value.id)
})
</script>

<template>
    <div class="flex-1 flex flex-col overflow-hidden">
        <!-- Nav tabs: Dashboard / Configurations / Tasks + Claude status badge -->
        <div class="flex items-stretch px-2 bg-white shrink-0 border-b border-stroke h-10">
            <button
                v-for="tab in TABS"
                :key="tab.id"
                :class="[
                    'bg-transparent cursor-pointer px-4 h-full text-[13px] transition-colors duration-100 relative border-b-2 -mb-px',
                    activeView === tab.id ? 'text-zinc-900 font-semibold border-accent' : 'text-zinc-500 font-normal border-transparent',
                ]"
                @click="selectTab(tab.id)"
            >
                {{ tab.label }}
            </button>

            <template v-if="activeProject">
                <div class="my-2 mx-1 w-px bg-stroke" />
                <div class="flex items-center gap-1.5 px-2">
                    <span v-if="activeStatus === 'running'" class="flex items-center gap-1.5 ml-2">
                        <DotsIndicator />
                        <span class="text-amber-700 text-[11px] font-mono">running</span>
                    </span>
                    <span v-else-if="activeStatus === 'done'" class="flex items-center gap-[5px] ml-1.5">
                        <span class="w-[7px] h-[7px] rounded-full bg-success" />
                        <span class="text-success text-[11px] font-mono">done</span>
                    </span>
                </div>
            </template>

            <!-- Global running indicator -->
            <div v-if="liveSessionCount > 0" class="flex items-center gap-2 pr-3 ml-auto">
                <DotsIndicator />
                <span class="text-amber-600 text-[12.5px] font-semibold font-mono">{{ liveSessionCount }} running</span>
            </div>
        </div>

        <div class="flex-1 flex overflow-hidden">
            <!-- Always mounted (display-toggled) so the terminal slot never unmounts under a live xterm. -->
            <div :class="['flex-1 overflow-hidden', showPmTerminal ? 'flex' : 'hidden']">
                <div ref="terminalSlot" data-testid="pm-terminal" class="flex-1 overflow-hidden p-2 box-border bg-[#f6f8fa]" />
            </div>

            <AgentsIndex v-if="showOverview" />

            <div v-if="!activeProject" class="flex-1 flex items-center justify-center">
                <span class="text-zinc-400 text-[13px]">No project selected</span>
            </div>

            <slot v-if="!showAgentsView" />
        </div>
    </div>
</template>
